language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
deploy:
  provider: npm
  email: "lukas.spirig@gmail.com"
  api_key: "ZWxdySPF9J9XXTMdTGGsYHtnE4IbYN38wGCCtFVAN4WThjnmozvePT9DY7BW/Bi7N+DytVNyMVG1gMyAXBkT3x446yx7IOtYlSDq97l1bwF30NOw4MTB00A8v8XEEfpV+U3dmgOw4NxsKiHVXO29j9Xr+Hyrit7kipulKuQVrwR4q8j8BS2cc3XtkogorWqX7aDKLl2HNwuBmfEVte9ivmWZry1UGBezsqdaUf0BgruvvctkgLcBmUHlt4JXD1EYyt1ffwxgG+a12WrhGIuMZQfCagrdMeyK6BOyMFxuliUOJ/Go5EAN6gHJhJ5mbbF5v3ribtYOvbIwe272bsWlXPo8lywXtkXPtddXeV31tRV9vvoVnPS63c00WwFagiQEUbpq+jrbHblziAHR/Clr2zqB3emXf5gtSmP5xhq1cR4vdJVOBZGG/NRs5gplW4Z3pZTCxWXkC6ymLLVtG1qDW1vXinExcGIw0UUcwhleaEPi9q/dZblZG49G7JB5ApOr5jseslZ0FhQdbb2RVQFFiiKKnogerGIein/Gk5Tlok+n6eAoDa9JBqn3OHephsNOid3AfrrLLuSjKxW725geVzx1bNE7I4Rnx7IJeUZiw+E0TQF3PeNjMIw1k4YBxhYLo5F+VuuK+joczzuvzIBXRR1Pya9n80BvHLpTeyFSlh4="
  skip_cleanup: true
  on:
    tags: true